apiVersion: v1
kind: Secret
metadata:
  name: github-registry-secret
  namespace: webhook-system
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "ghcr.io": {
          "auth": "<username>:<token> | base 64"
        }
      }
    }