apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: validate-webhook-tls
  namespace: webhook-system
  annotations:
    cert-manager.io/issue-temporary-certificate: "true"
spec:
  secretName: validate-webhook-tls
  duration: 8760h 
  renewBefore: 360h 
  subject:
    organizations:
      - Rancher Desktop
  commonName: "*.webhook-system.svc" 
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
  dnsNames:
    - "*.webhook-system"
    - "*.webhook-system.svc" 
    - "*.webhook-system.svc.cluster.local"
  issuerRef:
    name: rancher-desktop-ca
    kind: ClusterIssuer
